### ISSUE TITLE
Compatibility outside oh-my-zsh?

### ISSUE THREAD

**Issue by N4M3Z** [rutchkiwi/copyzshell#3]
Just wanted to ask whether this plugin is supposed to work outside oh-my-zsh framework? I am using `zgen` the way you write in your readme, however the aliases from `copyzshell.plugin.zsh` obviously cannot work for a folder structure different from that of `oh-my-zsh`:

```
alias copyshell=$ZSH/custom/plugins/copyzshell/copyzshell.zsh 
alias copyzshell=$ZSH/custom/plugins/copyzshell/copyzshell.zsh 
```

I also noticed there are `oh-my-zsh` paths in the `copyzshell.zsh` itself. Are you planning to support copying of ZSH config files in general, perhaps by having user providing the path?

**Comment by rutchkiwi** [comment]
Hey, I use oh-my-zsh myself, and haven't tested with antigen and zgen. So when you think about it, it of course doesn't work with anything else with the way it works now. I'll remove the references to antigen and zsh in the readme. 

That being said, I'm of course open to pull requests!

**Comment by N4M3Z** [comment]
Hi, don't change it, I will look into it and send a pull request eventually.

**Comment by rutchkiwi** [comment]
Too late! :p But yeah looking forward too it!
